### ISSUE TITLE
missing basic_streambuf implementation

### ISSUE THREAD

**Issue by matbech** [chriskohlhoff/networking-ts-impl#1]
Is the basic_streambuf implementation missing (basic_streambuf.hpp) or is this still work in progress where ultimately basic_streambuf will be replaced with the std::basic_streambuf version?

**Comment by chriskohlhoff** [comment]
`asio::basic_streambuf` isn't part of the draft standard networking TS. The replacement functionality is to use `std::string` or `std::vector` with `dynamic_buffer()`. E.g.:

    namespace net = std::experimental::net; // or namespace net = asio
    std::string s;
    net::read_until(my_socket, net::dynamic_buffer(s), '\n');
