### ISSUE TITLE
something like boost::asio::posix::stream_descriptor

### ISSUE THREAD

**Issue by ajneu** [chriskohlhoff/networking-ts-impl#3]
Hi,

we're successfully using [`boost::asio::posix::stream_descriptor`](http://www.boost.org/doc/libs/release/doc/html/boost_asio/reference/posix__stream_descriptor.html).

Is there a way of using this with the new networking-ts-impl?

Thanks.

PS: I've started converting the [Boost Asio timer tutorial](http://www.boost.org/doc/libs/release/doc/html/boost_asio/tutorial.html) to using networking-ts-impl.
See https://github.com/ajneu/networking-ts-impl-examples
I must admit: it took me quite a bit of time to figure out how to convert `strand::wrap` (with `bind_executor` !)

**Comment by chriskohlhoff** [comment]
> we're successfully using boost::asio::posix::stream_descriptor.
>
> Is there a way of using this with the new networking-ts-impl?

No. This repo is intended to be an implementation of only those facilities included in the draft networking TS. If you need those additional facilities you'll have to stick with asio.

**Comment by alexhultman** [comment]
@chriskohlhoff So you're saying the upcoming C++20 Networking does *not* have any feature to integrate with other non-C++20 Networking servers?

I was going to ask how much user space memory was needed per stream_descriptor (a proper implementation should be close to 4 bytes) but now I'm here and you're telling me there is not even something like this? I cannot have my own FD:s and have C++20 Networking's event-loop tell me the events? That's a major critical issue with this draft.

I know ASIO is not easy on memory, far worse than libuv and a couple of mountains worse than raw Linux epoll. Do you have any comment on this?

**Comment by ajneu** [comment]
> I know ASIO is not easy on memory, far worse than libuv and a couple of mountains worse than raw Linux epoll. Do you have any comment on this?

At least one can use allocators to ease on the free store (heap) usage a bit, regarding the handlers; which can be seen as a performance-boost.
There's an example [here](https://github.com/boostorg/asio/blob/develop/example/cpp11/allocation/server.cpp) ([here](http://www.boost.org/doc/html/boost_asio/examples/cpp11_examples.html))

(Yet... I don't think one can easily strip away **all** of Asio's free store usage, should one desire that...)

The allocation is around 152 bytes for the [read-handler](https://github.com/boostorg/asio/blob/f7fa336c91418458b80c33331f78dc7d367a226f/example/cpp11/allocation/server.cpp#L132), and around 224 bytes for the [write-handler](https://github.com/boostorg/asio/blob/f7fa336c91418458b80c33331f78dc7d367a226f/example/cpp11/allocation/server.cpp#L146).
