### ISSUE TITLE
add documentations?

### ISSUE THREAD

**Issue by AraHaan** [chriskohlhoff/networking-ts-impl#5]
As much as I would start going in and using this technical specification as asio is somewhat too big for my harddisc with boost on it for it. This forces me to use the TS for networking. What I need to use this library for is for things similar to python3's aiohttp package. Basically I want to use this to request an online resource ir server and get back an string that turns out to be an json type http response. I already use the json for modern c++ (https://github.com/nlohmann/json) for the data I plan to get and not cache to any file or anything so people cant even think of manipulating this sort of implementation I plan to use for an API I am making on c++.

Because of this I need document for this.

**Comment by chriskohlhoff** [comment]
Docs can now be found in a sister repository. Please see top-level README.md for link.
