### ISSUE TITLE
Is this the async IO to use for a new project?

### ISSUE THREAD

**Issue by akoolenbourke** [chriskohlhoff/networking-ts-impl#6]
Hi Chris. I'm going around in circles trying to get an understanding (Or find anyone why can tell me) of the best version of ASIO to use in a new, large, piece of work I am about to undertake. 

I see that this this repo is taken from ASIO so does this mean it's production ready? I would prefer to use something if it's going to more closely match the upcoming networking spec but only if it's production ready to at least the Boost/Standalone ASIO.

Thanks

**Comment by chriskohlhoff** [comment]
This project is simply a subset of asio, taken directly from the asio master branch, and with some simple namespace renaming applied.

I will answer your question under the original issue you raised against asio.
